"""
Step definitions for deterministic BDD execution.

These steps match the Gherkin generated by feature_generator.py.
Static POMs are used when available, otherwise DynamicPage resolves
elements via the DOM Knowledge Base (Qdrant RAG).
"""
from __future__ import annotations

import logging

import pytest
from pytest_bdd import given, when, then, parsers, scenarios

from core.pages.page_registry import PAGE_REGISTRY
from core.pages.dynamic_page import DynamicPage

logger = logging.getLogger(__name__)


pytestmark = pytest.mark.e2e

# Load all generated scenarios
scenarios("../../generated/features/")

# ── Current page context (set by navigate, used by DynamicPage lookup) ──
_current_page: str = ""

def _get_dynamic_page(pom_instances: dict) -> DynamicPage | None:
    """Return the DynamicPage matching the current navigation context."""
    global _current_page
    # Prefer the DynamicPage matching the last navigated page
    if _current_page and _current_page in pom_instances:
        pom = pom_instances[_current_page]
        if isinstance(pom, DynamicPage):
            return pom
    # Fall through to any DynamicPage
    for _name, pom in pom_instances.items():
        if isinstance(pom, DynamicPage):
            return pom
    return None


# ── Sub-page navigation map ───────────────────────────────────────
# Maps page names to their sidebar link text and direct URL paths.
# When navigating to a sub-page, we first try the sidebar link;
# if the current page doesn't have a sidebar (e.g. not logged in yet)
# we fall back to direct URL navigation.
_PAGE_URLS = {
    "Transfer Funds": "/parabank/transfer.htm",
    "Bill Pay": "/parabank/billpay.htm",
    "Request Loan": "/parabank/requestloan.htm",
    "Accounts Overview": "/parabank/overview.htm",
    "Open New Account": "/parabank/openaccount.htm",
    "Find Transactions": "/parabank/findtrans.htm",
    "Update Contact Info": "/parabank/updateprofile.htm",
}


# ── Given ─────────────────────────────────────────────────────────

@given(parsers.parse('I navigate to "{target}"'))
def step_navigate(page, pom_instances, target, base_url):
    """Navigate to a page URL or click a sidebar link.

    For login/home pages: goto base_url.
    For sub-pages (Transfer Funds, Bill Pay, etc.): try sidebar link first,
    fall back to direct URL.
    """
    logger.info("STEP: navigate to '%s' (base_url=%s)", target, base_url)
    global _current_page
    _current_page = target

    # Check if this is a sub-page navigation
    if target in _PAGE_URLS:
        # Try clicking the sidebar link first (text-based)
        try:
            sidebar_link = page.get_by_role("link", name=target)
            if sidebar_link.count() > 0 and sidebar_link.first.is_visible():
                sidebar_link.first.click(timeout=10000)
                page.wait_for_load_state("domcontentloaded", timeout=15000)
                logger.info("Navigated to '%s' via sidebar link", target)
                return
        except Exception:
            pass

        # Fallback: direct URL navigation
        url = base_url.rstrip("/").rsplit("/parabank", 1)[0] + _PAGE_URLS[target]
        logger.info("Navigating to '%s' via direct URL: %s", target, url)
        page.goto(url, timeout=60000, wait_until="domcontentloaded")
    else:
        # Default: navigate to base URL (login/home page)
        page.goto(base_url, timeout=60000, wait_until="domcontentloaded")


# ── When ──────────────────────────────────────────────────────────

@when(parsers.parse('I fill "{field}" with "{value}"'))
def step_fill(page, pom_instances, field, value):
    """Fill a field — resolved through POM SUPPORTED_FIELDS or DynamicPage.

    [EMPTY] sentinel clears the field (empty-field test).
    """
    actual_value = "" if value == "[EMPTY]" else value
    logger.info("STEP: fill '%s' with '%s'", field, actual_value)
    # Try static POMs first
    for _name, pom in pom_instances.items():
        if field in pom.SUPPORTED_FIELDS:
            pom.fill_field(field, actual_value)
            return
    # Fall through to DynamicPage matching current page
    dp = _get_dynamic_page(pom_instances)
    if dp:
        dp.fill_field(field, actual_value)
        return
    pytest.fail(f"Field '{field}' not found in any registered POM or DynamicPage")


@when(parsers.parse('I click "{field}"'))
def step_click(page, pom_instances, field):
    """Click a field — resolved through POM SUPPORTED_FIELDS or DynamicPage."""
    logger.info("STEP: click '%s'", field)
    # Try static POMs first
    for _name, pom in pom_instances.items():
        if field in pom.SUPPORTED_FIELDS:
            pom.click_field(field)
            try:
                page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            return
    # Fall through to DynamicPage matching current page
    dp = _get_dynamic_page(pom_instances)
    if dp:
        dp.click_field(field)
        try:
            page.wait_for_load_state("domcontentloaded", timeout=15000)
        except Exception:
            pass
        return
    pytest.fail(f"Field '{field}' not found in any registered POM or DynamicPage")


@when(parsers.parse('I select "{field}" with "{value}"'))
def step_select(page, pom_instances, field, value):
    """Select a dropdown option — resolved through DynamicPage."""
    logger.info("STEP: select '%s' with '%s'", field, value)
    dp = _get_dynamic_page(pom_instances)
    if dp:
        dp.select_field(field, value)
        return
    pytest.fail(f"Field '{field}' not found in any DynamicPage for select")


# ── Then ──────────────────────────────────────────────────────────

@then(parsers.parse('I verify "{field}" shows "{expected}"'))
def step_verify_text(page, pom_instances, field, expected):
    """Verify text — resolved through POM SUPPORTED_FIELDS or DynamicPage."""
    logger.info("STEP: verify '%s' shows '%s'", field, expected)
    # Try static POMs first
    for _name, pom in pom_instances.items():
        if field in pom.SUPPORTED_FIELDS:
            pom.verify_text(field, expected)
            return
    # Fall through to DynamicPage matching current page
    dp = _get_dynamic_page(pom_instances)
    if dp:
        dp.verify_text(field, expected)
        return
    pytest.fail(f"Field '{field}' not found in any registered POM or DynamicPage")
